import {
  Geist,
  Geist_Mono,
} from 'next/font/google';
import Head from 'next/head';

import styles from '@/styles/Home.module.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>INNOV-DEV-API </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>

          Page d'accueil INNOV DEV/API /TAAM-BETA
          <div>
            Plus d'info : <a href="mailto:groupinnov.dev@gmail.com">Contacter Group Innov.Dev</a>
          </div>
        </main>
        <footer className={styles.footer}>
          Copyright Innov.Dev group -2025 Tout droit réservé.

        </footer>
      </div>
    </>
  );
}
